import {
  Users,
  BarChart3,
  ClipboardMinus,
  Calendar,
  IdCardLanyard,
  UserCircle,
  UsersRound,
  BellRing,
} from "lucide-react"

export const menuConfig = [
      {
    key: "Consultas",
    label: "Consultas",
    path: "/consultas",
    icon: ClipboardMinus,
    roles: ["USER", "MANAGER"],
  },
  {
    key: "funcionarios",
    label: "Funcionários",
    path: "/funcionarios",
    icon: IdCardLanyard,
    roles: ["ADMIN"],
  },
  {
    key: "pacientes",
    label: "Pacientes",
    path: "/pacientes",
    icon: Users,
    roles: ["USER", "MANAGER", "ADMIN", "SCHEDULER"],
  },
  {
    key: "dashboard",
    label: "Dashboard",
    path: "/dashboard",
    icon: BarChart3,
    roles: ["ADMIN"],
  },
  // {
  //   key: "ficha-clinica",
  //   label: "Ficha Clínica",
  //   path: "/pacientes/ficha-clinica",
  //   icon: ClipboardMinus,
  //   roles: ["USER"],
  // },
  // {
  //   key: "consulta-atual",
  //   label: "Consulta Atual",
  //   path: "/pacientes/consulta-atual",
  //   icon: ClipboardMinus,
  //   roles: ["USER"],
  // },
  // {
  //   key: "consultas-antigas",
  //   label: "Consultas Antigas",
  //   path: "/pacientes/consultas-antigas",
  //   icon: ClipboardMinus,
  //   roles: ["USER"],
  // },
  {
    key: "agendamento-consulta",
    label: "Agendamento Consulta",
    path: "/agendamento-consulta",
    icon: Calendar,
    roles: ["ADMIN", "SCHEDULER"],
  },
    {
    key: "responsaveis",
    label: "Responsáveis",
    path: "/responsaveis",
    icon: IdCardLanyard,
    roles: ["SCHEDULER", "ADMIN"],
  },
  {
    key: "subordinados",
    label: "Meus Subordinados",
    path: "/subordinados",
    icon: UsersRound,
    roles: ["MANAGER"],
  },
  {
    key: "recorrencias-a-vencer",
    label: "Recorrências",
    path: "/recorrencias-a-vencer",
    icon: BellRing,
    roles: ["SCHEDULER"],
  },
  {
    key: "meu-perfil",
    label: "Meu Perfil",
    path: "/meu-perfil",
    icon: UserCircle,
    roles: ["USER", "ADMIN", "MANAGER", "SCHEDULER"],
  },
]